// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_9lFy1rIk9J9_aYuFxkHMsTa9auJIzyA',
    appId: '1:59357451653:web:81157a9ce2846305ada0ec',
    messagingSenderId: '59357451653',
    projectId: 'team-alpha-bar',
    authDomain: 'team-alpha-bar.firebaseapp.com',
    storageBucket: 'team-alpha-bar.appspot.com',
    measurementId: 'G-9P1ZSS4RF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmhcshXErmoQwgQy3z3L47IG5GGNRkN7I',
    appId: '1:59357451653:android:3d2ab6f6f04d2574ada0ec',
    messagingSenderId: '59357451653',
    projectId: 'team-alpha-bar',
    storageBucket: 'team-alpha-bar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5EMpVGXTz6LR-GmEajWzq2fh5LpwKw4',
    appId: '1:59357451653:ios:d333908ae9c70eddada0ec',
    messagingSenderId: '59357451653',
    projectId: 'team-alpha-bar',
    storageBucket: 'team-alpha-bar.appspot.com',
    iosBundleId: 'com.example.teamAlphaBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5EMpVGXTz6LR-GmEajWzq2fh5LpwKw4',
    appId: '1:59357451653:ios:b4de71e32d4fd4faada0ec',
    messagingSenderId: '59357451653',
    projectId: 'team-alpha-bar',
    storageBucket: 'team-alpha-bar.appspot.com',
    iosBundleId: 'com.example.teamAlphaBar.RunnerTests',
  );
}
